=== akalsan/aiw-i2b2-etl/src/test/resources/testData.dtd
<!ELEMENT dataset (
    CPT_EVENT*,
    ENCOUNTER*,
    ICD9D_EVENT*,
    ICD9P_EVENT*,
    LABS_EVENT*,
    MEDS_EVENT*,
    PATIENT*,
    PROVIDER*,
    VITALS_EVENT*)>

<!ELEMENT CPT_EVENT EMPTY>
<!ATTLIST CPT_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
>

<!ELEMENT ENCOUNTER EMPTY>
<!ATTLIST ENCOUNTER
    ENCOUNTER_KEY CDATA #REQUIRED
    PATIENT_KEY CDATA #REQUIRED
    PROVIDER_KEY CDATA #REQUIRED
    TS_START CDATA #IMPLIED
    TS_END CDATA #IMPLIED
    ENCOUNTER_TYPE CDATA #IMPLIED
    DISCHARGE_DISP CDATA #IMPLIED
>

<!ELEMENT ICD9D_EVENT EMPTY>
<!ATTLIST ICD9D_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
    RANK CDATA #REQUIRED
    SOURCE CDATA #REQUIRED
>

<!ELEMENT ICD9P_EVENT EMPTY>
<!ATTLIST ICD9P_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
>

<!ELEMENT LABS_EVENT EMPTY>
<!ATTLIST LABS_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
    RESULT_STR CDATA #IMPLIED
    RESULT_NUM CDATA #IMPLIED
    UNITS CDATA #IMPLIED
    FLAG CDATA #IMPLIED
>

<!ELEMENT MEDS_EVENT EMPTY>
<!ATTLIST MEDS_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
>

<!ELEMENT PATIENT EMPTY>
<!ATTLIST PATIENT
    PATIENT_KEY CDATA #REQUIRED
    FIRST_NAME CDATA #IMPLIED
    LAST_NAME CDATA #IMPLIED
    DOB CDATA #IMPLIED
    LANGUAGE CDATA #IMPLIED
    MARITAL_STATUS CDATA #IMPLIED
    RACE CDATA #IMPLIED
    GENDER CDATA #IMPLIED
>

<!ELEMENT PROVIDER EMPTY>
<!ATTLIST PROVIDER
    PROVIDER_KEY CDATA #REQUIRED
    FIRST_NAME CDATA #IMPLIED
    LAST_NAME CDATA #IMPLIED
>

<!ELEMENT VITALS_EVENT EMPTY>
<!ATTLIST VITALS_EVENT
    EVENT_KEY CDATA #REQUIRED
    ENCOUNTER_KEY CDATA #REQUIRED
    TS_OBX CDATA #IMPLIED
    ENTITY_ID CDATA #REQUIRED
    RESULT_STR CDATA #IMPLIED
    RESULT_NUM CDATA #IMPLIED
    UNITS CDATA #IMPLIED
    FLAG CDATA #IMPLIED
>

=== akalsan/aiw-i2b2-etl/src/test/resources/testData.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "testData.dtd">
<dataset>
  <CPT_EVENT/>
  <ENCOUNTER ENCOUNTER_KEY="0" PATIENT_KEY="0" PROVIDER_KEY="52" TS_START="2006-08-23 16:20:18.0" TS_END="2006-08-28 16:20:18.0" ENCOUNTER_TYPE="LONGTERMCARE" DISCHARGE_DISP="DSCHXFERTOOTHER" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="1" PATIENT_KEY="0" PROVIDER_KEY="42" TS_START="2007-02-27 13:20:15.0" TS_END="2007-03-07 13:20:15.0" ENCOUNTER_TYPE="TECVISIT" DISCHARGE_DISP="INSURANCECARRIERCHANGE" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="2" PATIENT_KEY="0" PROVIDER_KEY="68" TS_START="2007-03-21 04:33:44.0" TS_END="2007-03-30 04:33:44.0" ENCOUNTER_TYPE="NEWBORN" DISCHARGE_DISP="TOFEDERALHOSPITAL" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="3" PATIENT_KEY="0" PROVIDER_KEY="22" TS_START="2008-01-10 16:15:26.0" TS_END="2008-01-15 16:15:26.0" ENCOUNTER_TYPE="AMBULATORYSURGERY" DISCHARGE_DISP="AGAINSTMEDICALADVICEWITHFOLLOWUP" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="4" PATIENT_KEY="0" PROVIDER_KEY="9" TS_START="2009-05-18 07:26:31.0" TS_END="2009-05-22 07:26:31.0" ENCOUNTER_TYPE="HISTORY" DISCHARGE_DISP="ADMITASINPATIENTTHISHOSP" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="5" PATIENT_KEY="1" PROVIDER_KEY="9" TS_START="2006-09-03 09:47:43.0" TS_END="2006-09-12 09:47:43.0" ENCOUNTER_TYPE="EMERGENCY" DISCHARGE_DISP="SHORTTERMHOSPITAL" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="6" PATIENT_KEY="1" PROVIDER_KEY="80" TS_START="2007-07-15 14:09:03.0" TS_END="2007-07-18 14:09:03.0" ENCOUNTER_TYPE="REHABRECURRING" DISCHARGE_DISP="HOSPICEHOME" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="7" PATIENT_KEY="1" PROVIDER_KEY="37" TS_START="2007-12-29 02:17:20.0" TS_END="2008-01-02 02:17:20.0" ENCOUNTER_TYPE="OBSERVATION" DISCHARGE_DISP="LONGTERMCAREHOSPITAL" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="8" PATIENT_KEY="1" PROVIDER_KEY="126" TS_START="2008-05-15 06:42:05.0" TS_END="2008-05-21 06:42:05.0" ENCOUNTER_TYPE="RECONSTRUCTEDPT" DISCHARGE_DISP="HOMEHEALTHSERVICE" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="9" PATIENT_KEY="1" PROVIDER_KEY="79" TS_START="2008-11-20 20:58:36.0" TS_END="2008-11-30 20:58:36.0" ENCOUNTER_TYPE="TREATRMOP" DISCHARGE_DISP="INTERMEDIATECARE" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="10" PATIENT_KEY="1" PROVIDER_KEY="72" TS_START="2010-09-02 12:56:18.0" TS_END="2010-09-07 12:56:18.0" ENCOUNTER_TYPE="TREATRMOP" DISCHARGE_DISP="TOCOURTLAWENFORCE" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="11" PATIENT_KEY="2" PROVIDER_KEY="108" TS_START="2006-12-15 18:29:21.0" TS_END="2006-12-17 18:29:21.0" ENCOUNTER_TYPE="VIPRECURRING" DISCHARGE_DISP="DISCHARGETOPSYCHIATRICFACILITY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="12" PATIENT_KEY="3" PROVIDER_KEY="117" TS_START="2008-03-21 00:55:44.0" TS_END="2008-03-26 00:55:44.0" ENCOUNTER_TYPE="SPECIMEN" DISCHARGE_DISP="MCRAPPRVDSWINGBED" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="13" PATIENT_KEY="3" PROVIDER_KEY="11" TS_START="2010-03-24 00:30:59.0" TS_END="2010-03-27 00:30:59.0" ENCOUNTER_TYPE="HLAQC" DISCHARGE_DISP="INTERNALTRANSFERPERLEGALGUIDELINES" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="14" PATIENT_KEY="4" PROVIDER_KEY="109" TS_START="2006-11-17 02:09:49.0" TS_END="2006-11-28 02:09:49.0" ENCOUNTER_TYPE="SPECIMEN" DISCHARGE_DISP="SAMEINSTFOROUTPATIENTSERVICES" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="15" PATIENT_KEY="4" PROVIDER_KEY="74" TS_START="2007-03-25 06:53:57.0" TS_END="2007-04-01 06:53:57.0" ENCOUNTER_TYPE="HLAQC" DISCHARGE_DISP="INPATIENT" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="16" PATIENT_KEY="4" PROVIDER_KEY="127" TS_START="2007-11-03 21:19:07.0" TS_END="2007-11-13 20:19:07.0" ENCOUNTER_TYPE="IPCANCEL" DISCHARGE_DISP="EXPIRED" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="17" PATIENT_KEY="4" PROVIDER_KEY="30" TS_START="2008-04-17 01:59:23.0" TS_END="2008-04-25 01:59:23.0" ENCOUNTER_TYPE="HLAQC" DISCHARGE_DISP="STILLAPATIENT" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="18" PATIENT_KEY="4" PROVIDER_KEY="31" TS_START="2008-05-29 10:00:34.0" TS_END="2008-06-01 10:00:34.0" ENCOUNTER_TYPE="IPCANCEL" DISCHARGE_DISP="XFERTOPSYCHHOSP" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="19" PATIENT_KEY="4" PROVIDER_KEY="15" TS_START="2009-03-17 19:38:40.0" TS_END="2009-03-31 19:38:40.0" ENCOUNTER_TYPE="SPECIMEN" DISCHARGE_DISP="RETURNTRANSFER" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="20" PATIENT_KEY="4" PROVIDER_KEY="68" TS_START="2009-09-03 07:33:33.0" TS_END="2009-09-15 07:33:33.0" ENCOUNTER_TYPE="EMERGENCY" DISCHARGE_DISP="HOSPICEHOME" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="21" PATIENT_KEY="4" PROVIDER_KEY="6" TS_START="2011-07-04 08:07:02.0" TS_END="2011-07-15 08:07:02.0" ENCOUNTER_TYPE="NONPTMISCELLANEOUS" DISCHARGE_DISP="OTHERREHABFACILITY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="22" PATIENT_KEY="5" PROVIDER_KEY="28" TS_START="2010-10-01 16:19:21.0" TS_END="2010-10-08 16:19:21.0" ENCOUNTER_TYPE="REHABRECURRING" DISCHARGE_DISP="INTERMEDIATECARE" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="23" PATIENT_KEY="5" PROVIDER_KEY="20" TS_START="2011-02-03 09:38:11.0" TS_END="2011-02-05 09:38:11.0" ENCOUNTER_TYPE="MEDICALRECORDS" DISCHARGE_DISP="HOMECAREIVTHERAPY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="24" PATIENT_KEY="6" PROVIDER_KEY="58" TS_START="2006-09-13 00:30:03.0" TS_END="2006-09-22 00:30:03.0" ENCOUNTER_TYPE="RECONSTRUCTEDPT" DISCHARGE_DISP="AGAINSTMEDICALADVICE" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="25" PATIENT_KEY="6" PROVIDER_KEY="119" TS_START="2008-11-07 14:29:50.0" TS_END="2008-11-19 14:29:50.0" ENCOUNTER_TYPE="NEWBORN" DISCHARGE_DISP="TOCOURTLAWENFORCE" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="26" PATIENT_KEY="6" PROVIDER_KEY="94" TS_START="2008-12-20 15:14:23.0" TS_END="2009-01-02 15:14:23.0" ENCOUNTER_TYPE="TECVISIT" DISCHARGE_DISP="INTERMEDIATECARE" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="27" PATIENT_KEY="6" PROVIDER_KEY="122" TS_START="2010-07-24 04:09:43.0" TS_END="2010-08-06 04:09:43.0" ENCOUNTER_TYPE="VIPRECURRING" DISCHARGE_DISP="STILLAPATIENT" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="28" PATIENT_KEY="7" PROVIDER_KEY="101" TS_START="2006-08-22 04:34:31.0" TS_END="2006-08-27 04:34:31.0" ENCOUNTER_TYPE="SPECIMEN" DISCHARGE_DISP="INPATIENT" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="29" PATIENT_KEY="7" PROVIDER_KEY="17" TS_START="2006-11-18 14:03:50.0" TS_END="2006-11-28 14:03:50.0" ENCOUNTER_TYPE="EMERGENCY" DISCHARGE_DISP="AGAINSTMEDICALADVICEWITHFOLLOWUP" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="30" PATIENT_KEY="7" PROVIDER_KEY="123" TS_START="2007-11-14 04:50:01.0" TS_END="2007-11-24 04:50:01.0" ENCOUNTER_TYPE="NEWBORN" DISCHARGE_DISP="EXPIREDATOTHERFACILITY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="31" PATIENT_KEY="7" PROVIDER_KEY="109" TS_START="2008-01-13 14:31:44.0" TS_END="2008-01-25 14:31:44.0" ENCOUNTER_TYPE="NONPTMISCELLANEOUS" DISCHARGE_DISP="SHORTTERMHOSPITAL" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="32" PATIENT_KEY="7" PROVIDER_KEY="103" TS_START="2008-07-24 12:42:58.0" TS_END="2008-08-03 12:42:58.0" ENCOUNTER_TYPE="UNIDENTIFIEDACCT" DISCHARGE_DISP="DISCHARGEFOROTHERREASONWITHFOLLOWUP" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="33" PATIENT_KEY="7" PROVIDER_KEY="109" TS_START="2009-05-31 09:33:03.0" TS_END="2009-06-11 09:33:03.0" ENCOUNTER_TYPE="MEDICALRECORDS" DISCHARGE_DISP="DescriptionMissing" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="34" PATIENT_KEY="7" PROVIDER_KEY="125" TS_START="2010-11-26 12:03:31.0" TS_END="2010-12-06 12:03:31.0" ENCOUNTER_TYPE="TECVISIT" DISCHARGE_DISP="SHORTTERMHOSPITAL" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="35" PATIENT_KEY="7" PROVIDER_KEY="63" TS_START="2010-12-25 02:28:25.0" TS_END="2010-12-29 02:28:25.0" ENCOUNTER_TYPE="MEDICALRECORDS" DISCHARGE_DISP="HOMEHEALTHSERVICE" CREATE_DATE="2015-01-01 00:00:00.0" DELETE_DATE="2016-02-08 16:20:18.0"/>
  <ENCOUNTER ENCOUNTER_KEY="36" PATIENT_KEY="7" PROVIDER_KEY="31" TS_START="2011-01-21 16:05:08.0" TS_END="2011-01-24 16:05:08.0" ENCOUNTER_TYPE="INFUSIONSINGLEVISIT" DISCHARGE_DISP="DSCHXFERTOOTHER" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="37" PATIENT_KEY="8" PROVIDER_KEY="9" TS_START="2007-07-11 11:49:36.0" TS_END="2007-07-23 11:49:36.0" ENCOUNTER_TYPE="RECONSTRUCTEDPT" DISCHARGE_DISP="STILLAPATIENT" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="38" PATIENT_KEY="9" PROVIDER_KEY="55" TS_START="2010-10-21 18:04:32.0" TS_END="2010-11-04 18:04:32.0" ENCOUNTER_TYPE="TECVISIT" DISCHARGE_DISP="DISCHARGETOPSYCHIATRICFACILITY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="39" PATIENT_KEY="10" PROVIDER_KEY="123" TS_START="2007-06-17 10:29:46.0" TS_END="2007-06-21 10:29:46.0" ENCOUNTER_TYPE="DescriptionMissing" DISCHARGE_DISP="EXPIREDATOTHERFACILITY" CREATE_DATE="2015-01-01 00:00:00.0"/>
  <ENCOUNTER ENCOUNTER_KEY="40" PATIENT_KEY="10" PROVIDER_KEY="124" TS_START="2007-08-27 07:22:41.0" TS_END="2007-09-02 07:22:41.0" ENCOUNTER_TYPE="VIPRECURRING" DISCHARGE_DISP="ADMITASINPATIENTTHISHOSP" CREATE_DATE="2015-01-01 00:00:00.0"/>
