=== akalsan/aiw-i2b2-etl/src/test/resources/truth/i2b2LoadTestData.dtd
<!ELEMENT dataset (
    ARCHIVE_OBSERVATION_FACT*,
    CONCEPT_DIMENSION*,
    EK_REJECTED_OBSERVATION_FACT*,
    EK_TEMP_CONCEPT*,
    EK_TEMP_ENCOUNTER_MAPPING*,
    EK_TEMP_MODIFIER*,
    EK_TEMP_OBSERVATION*,
    EK_TEMP_OBSERVATION_COMPLETE*,
    EK_TEMP_PATIENT*,
    EK_TEMP_PATIENT_MAPPING*,
    EK_TEMP_PROVIDER*,
    EK_TEMP_VISIT*,
    ENCOUNTER_MAPPING*,
    MODIFIER_DIMENSION*,
    OBSERVATION_FACT*,
    PATIENT_DIMENSION*,
    PATIENT_MAPPING*,
    PROVIDER_DIMENSION*,
    REJECTED_OBSERVATION_FACT*,
    VISIT_DIMENSION*,
    DATABASECHANGELOG*,
    DATABASECHANGELOGLOCK*)>

<!ELEMENT ARCHIVE_OBSERVATION_FACT EMPTY>
<!ATTLIST ARCHIVE_OBSERVATION_FACT
    ENCOUNTER_NUM CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    CONCEPT_CD CDATA #IMPLIED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
    ARCHIVE_UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT CONCEPT_DIMENSION EMPTY>
<!ATTLIST CONCEPT_DIMENSION
    CONCEPT_PATH CDATA #IMPLIED
    CONCEPT_CD CDATA #IMPLIED
    NAME_CHAR CDATA #IMPLIED
    CONCEPT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT EK_REJECTED_OBSERVATION_FACT EMPTY>
<!ATTLIST EK_REJECTED_OBSERVATION_FACT
    ENCOUNTER_NUM CDATA #IMPLIED
    ENCOUNTER_ID CDATA #REQUIRED
    ENCOUNTER_ID_SOURCE CDATA #REQUIRED
    CONCEPT_CD CDATA #REQUIRED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_ID CDATA #REQUIRED
    PATIENT_ID_SOURCE CDATA #REQUIRED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
    REASON CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_CONCEPT EMPTY>
<!ATTLIST EK_TEMP_CONCEPT
    CONCEPT_CD CDATA #REQUIRED
    CONCEPT_PATH CDATA #REQUIRED
    NAME_CHAR CDATA #IMPLIED
    CONCEPT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_ENCOUNTER_MAPPING EMPTY>
<!ATTLIST EK_TEMP_ENCOUNTER_MAPPING
    ENCOUNTER_MAP_ID CDATA #REQUIRED
    ENCOUNTER_MAP_ID_SOURCE CDATA #REQUIRED
    PATIENT_MAP_ID CDATA #IMPLIED
    PATIENT_MAP_ID_SOURCE CDATA #IMPLIED
    ENCOUNTER_ID CDATA #REQUIRED
    ENCOUNTER_ID_SOURCE CDATA #IMPLIED
    ENCOUNTER_NUM CDATA #IMPLIED
    ENCOUNTER_MAP_ID_STATUS CDATA #IMPLIED
    PROCESS_STATUS_FLAG CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_MODIFIER EMPTY>
<!ATTLIST EK_TEMP_MODIFIER
    MODIFIER_CD CDATA #REQUIRED
    MODIFIER_PATH CDATA #REQUIRED
    NAME_CHAR CDATA #IMPLIED
    MODIFIER_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_OBSERVATION EMPTY>
<!ATTLIST EK_TEMP_OBSERVATION
    ENCOUNTER_NUM CDATA #IMPLIED
    ENCOUNTER_ID CDATA #REQUIRED
    ENCOUNTER_ID_SOURCE CDATA #REQUIRED
    CONCEPT_CD CDATA #REQUIRED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_ID CDATA #REQUIRED
    PATIENT_ID_SOURCE CDATA #REQUIRED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_OBSERVATION_COMPLETE EMPTY>
<!ATTLIST EK_TEMP_OBSERVATION_COMPLETE
    ENCOUNTER_NUM CDATA #IMPLIED
    ENCOUNTER_ID CDATA #REQUIRED
    ENCOUNTER_ID_SOURCE CDATA #REQUIRED
    CONCEPT_CD CDATA #REQUIRED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_ID CDATA #REQUIRED
    PATIENT_ID_SOURCE CDATA #REQUIRED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_PATIENT EMPTY>
<!ATTLIST EK_TEMP_PATIENT
    PATIENT_ID CDATA #IMPLIED
    PATIENT_ID_SOURCE CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    VITAL_STATUS_CD CDATA #IMPLIED
    BIRTH_DATE CDATA #IMPLIED
    DEATH_DATE CDATA #IMPLIED
    SEX_CD CDATA #IMPLIED
    AGE_IN_YEARS_NUM CDATA #IMPLIED
    LANGUAGE_CD CDATA #IMPLIED
    RACE_CD CDATA #IMPLIED
    MARITAL_STATUS_CD CDATA #IMPLIED
    RELIGION_CD CDATA #IMPLIED
    ZIP_CD CDATA #IMPLIED
    STATECITYZIP_PATH CDATA #IMPLIED
    PATIENT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_PATIENT_MAPPING EMPTY>
<!ATTLIST EK_TEMP_PATIENT_MAPPING
    PATIENT_MAP_ID CDATA #IMPLIED
    PATIENT_MAP_ID_SOURCE CDATA #IMPLIED
    PATIENT_ID_STATUS CDATA #IMPLIED
    PATIENT_ID CDATA #IMPLIED
    PATIENT_ID_SOURCE CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_MAP_ID_STATUS CDATA #IMPLIED
    PROCESS_STATUS_FLAG CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_PROVIDER EMPTY>
<!ATTLIST EK_TEMP_PROVIDER
    PROVIDER_ID CDATA #REQUIRED
    PROVIDER_PATH CDATA #REQUIRED
    NAME_CHAR CDATA #IMPLIED
    PROVIDER_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT EK_TEMP_VISIT EMPTY>
<!ATTLIST EK_TEMP_VISIT
    ENCOUNTER_ID CDATA #REQUIRED
    ENCOUNTER_ID_SOURCE CDATA #REQUIRED
    PATIENT_ID CDATA #REQUIRED
    PATIENT_ID_SOURCE CDATA #REQUIRED
    ENCOUNTER_NUM CDATA #IMPLIED
    INOUT_CD CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    LOCATION_PATH CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    VISIT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    ACTIVE_STATUS_CD CDATA #IMPLIED
    LENGTH_OF_STAY CDATA #IMPLIED
>

<!ELEMENT ENCOUNTER_MAPPING EMPTY>
<!ATTLIST ENCOUNTER_MAPPING
    ENCOUNTER_IDE CDATA #IMPLIED
    ENCOUNTER_IDE_SOURCE CDATA #IMPLIED
    PROJECT_ID CDATA #IMPLIED
    ENCOUNTER_NUM CDATA #IMPLIED
    PATIENT_IDE CDATA #IMPLIED
    PATIENT_IDE_SOURCE CDATA #IMPLIED
    ENCOUNTER_IDE_STATUS CDATA #IMPLIED
    UPLOAD_DATE CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT MODIFIER_DIMENSION EMPTY>
<!ATTLIST MODIFIER_DIMENSION
    MODIFIER_PATH CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    NAME_CHAR CDATA #IMPLIED
    MODIFIER_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT OBSERVATION_FACT EMPTY>
<!ATTLIST OBSERVATION_FACT
    ENCOUNTER_NUM CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    CONCEPT_CD CDATA #IMPLIED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT PATIENT_DIMENSION EMPTY>
<!ATTLIST PATIENT_DIMENSION
    PATIENT_NUM CDATA #IMPLIED
    VITAL_STATUS_CD CDATA #IMPLIED
    BIRTH_DATE CDATA #IMPLIED
    DEATH_DATE CDATA #IMPLIED
    SEX_CD CDATA #IMPLIED
    AGE_IN_YEARS_NUM CDATA #IMPLIED
    LANGUAGE_CD CDATA #IMPLIED
    RACE_CD CDATA #IMPLIED
    MARITAL_STATUS_CD CDATA #IMPLIED
    RELIGION_CD CDATA #IMPLIED
    ZIP_CD CDATA #IMPLIED
    STATECITYZIP_PATH CDATA #IMPLIED
    INCOME_CD CDATA #IMPLIED
    PATIENT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT PATIENT_MAPPING EMPTY>
<!ATTLIST PATIENT_MAPPING
    PATIENT_IDE CDATA #IMPLIED
    PATIENT_IDE_SOURCE CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_IDE_STATUS CDATA #IMPLIED
    PROJECT_ID CDATA #IMPLIED
    UPLOAD_DATE CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT PROVIDER_DIMENSION EMPTY>
<!ATTLIST PROVIDER_DIMENSION
    PROVIDER_ID CDATA #IMPLIED
    PROVIDER_PATH CDATA #IMPLIED
    NAME_CHAR CDATA #IMPLIED
    PROVIDER_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT REJECTED_OBSERVATION_FACT EMPTY>
<!ATTLIST REJECTED_OBSERVATION_FACT
    ENCOUNTER_NUM CDATA #IMPLIED
    ENCOUNTER_ID CDATA #IMPLIED
    ENCOUNTER_ID_SOURCE CDATA #IMPLIED
    CONCEPT_CD CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    PATIENT_ID CDATA #IMPLIED
    PATIENT_ID_SOURCE CDATA #IMPLIED
    PROVIDER_ID CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    MODIFIER_CD CDATA #IMPLIED
    INSTANCE_NUM CDATA #IMPLIED
    VALTYPE_CD CDATA #IMPLIED
    TVAL_CHAR CDATA #IMPLIED
    NVAL_NUM CDATA #IMPLIED
    VALUEFLAG_CD CDATA #IMPLIED
    QUANTITY_NUM CDATA #IMPLIED
    CONFIDENCE_NUM CDATA #IMPLIED
    OBSERVATION_BLOB CDATA #IMPLIED
    UNITS_CD CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
    REASON CDATA #IMPLIED
>

<!ELEMENT VISIT_DIMENSION EMPTY>
<!ATTLIST VISIT_DIMENSION
    ENCOUNTER_NUM CDATA #IMPLIED
    PATIENT_NUM CDATA #IMPLIED
    ACTIVE_STATUS_CD CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    INOUT_CD CDATA #IMPLIED
    LOCATION_CD CDATA #IMPLIED
    LOCATION_PATH CDATA #IMPLIED
    LENGTH_OF_STAY CDATA #IMPLIED
    VISIT_BLOB CDATA #IMPLIED
    UPDATE_DATE CDATA #IMPLIED
    DOWNLOAD_DATE CDATA #IMPLIED
    IMPORT_DATE CDATA #IMPLIED
    SOURCESYSTEM_CD CDATA #IMPLIED
    UPLOAD_ID CDATA #IMPLIED
>

<!ELEMENT DATABASECHANGELOG EMPTY>
<!ATTLIST DATABASECHANGELOG
    ID CDATA #IMPLIED
    AUTHOR CDATA #IMPLIED
    FILENAME CDATA #IMPLIED
    DATEEXECUTED CDATA #IMPLIED
    ORDEREXECUTED CDATA #IMPLIED
    EXECTYPE CDATA #IMPLIED
    MD5SUM CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    COMMENTS CDATA #IMPLIED
    LIQUIBASE CDATA #IMPLIED
>

<!ELEMENT DATABASECHANGELOGLOCK EMPTY>
<!ATTLIST DATABASECHANGELOGLOCK
    ID CDATA #IMPLIED
    LOCKED CDATA #IMPLIED
>

=== akalsan/aiw-i2b2-etl/src/test/resources/truth/i2b2LoadNoDerivedVariablesLowerDateBoundTestData.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "i2b2LoadTestData.dtd">
<dataset>
  <ARCHIVE_OBSERVATION_FACT/>
  <CONCEPT_DIMENSION/>
  <EK_REJECTED_OBSERVATION_FACT/>
  <EK_TEMP_CONCEPT CONCEPT_CD="DiastolicBloodPressure" CONCEPT_PATH="\EK\VitalSign\DiastolicBloodPressure\" NAME_CHAR="Diastolic Blood Pressure" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="HeartRate" CONCEPT_PATH="\EK\VitalSign\HeartRate\" NAME_CHAR="Heart Rate" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="SystolicBloodPressure" CONCEPT_PATH="\EK\VitalSign\SystolicBloodPressure\" NAME_CHAR="Systolic Blood Pressure" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="RespiratoryRate" CONCEPT_PATH="\EK\VitalSign\RespiratoryRate\" NAME_CHAR="Respiratory Rate" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="O2Saturation" CONCEPT_PATH="\EK\VitalSign\O2Saturation\" NAME_CHAR="Oxygen Saturation" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="BodyMassIndex" CONCEPT_PATH="\EK\VitalSign\BodyMassIndex\" NAME_CHAR="Body mass index" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:72" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:72-75\ICD9:72\" NAME_CHAR="Forceps, vacuum, and breech delivery" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:77" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:76-84\ICD9:77\" NAME_CHAR="Incision, excision, and division of other bones" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="LAB:8400010" CONCEPT_PATH="\EK\LAB:LabTest\LAB:Other\LAB:8400010\" NAME_CHAR="AP WHITE BLOOD CELL COUNT" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="LAB:8007694" CONCEPT_PATH="\EK\LAB:LabTest\LAB:Other\LAB:8007694\" NAME_CHAR="SC QM CODES AND STAINS" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="LAB:2000820" CONCEPT_PATH="\EK\LAB:LabTest\LAB:CBC\LAB:2000820\" NAME_CHAR="PLATELET CT" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureCore" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureCore\" NAME_CHAR="Temperature (C) Core" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureAxillary" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureAxillary\" NAME_CHAR="Temperature (C) Axillary" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureNOS" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureNOS\" NAME_CHAR="Temperature" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureRectal" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureRectal\" NAME_CHAR="Temperature (C) Rectal" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureOral" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureOral\" NAME_CHAR="Temperature (C) Oral" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="TemperatureTympanic" CONCEPT_PATH="\EK\VitalSign\Temperature\TemperatureTympanic\" NAME_CHAR="Temperature (C) Tympanic" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:985" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:800-999\ICD9:960-989\ICD9:985\" NAME_CHAR="Toxic effect of other metals" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:947" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:800-999\ICD9:940-949\ICD9:947\" NAME_CHAR="Burn of internal organs" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:770.7" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:760-779\ICD9:770\ICD9:770.7\" NAME_CHAR="Wilson-Mikity syndrome" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:66.9" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:65-71\ICD9:66\ICD9:66.9\" NAME_CHAR="Other operations on fallopian tubes" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:48.5" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:42-54\ICD9:48\ICD9:48.5\" NAME_CHAR="Abdominoperineal resection of rectum" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:74.9" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:72-75\ICD9:74\ICD9:74.9\" NAME_CHAR="Cesarean section of unspecified type" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:96.2" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:87-99\ICD9:96\ICD9:96.2\" NAME_CHAR="Nonoperative dilation and manipulation" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:92.2" CONCEPT_PATH="\EK\ICD9:Procedures\ICD9:87-99\ICD9:92\ICD9:92.2\" NAME_CHAR="Therapeutic radiology and nuclear medicine" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:800.8" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:800-999\ICD9:800-804\ICD9:800\ICD9:800.8\" NAME_CHAR="Open fracture of vault of skull with other and unspecified intracranial hemorrhage" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:962.6" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:800-999\ICD9:960-989\ICD9:962\ICD9:962.6\" NAME_CHAR="Poisoning by parathyroid hormone or parathyroid derivative NOS" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:943.4" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:800-999\ICD9:940-949\ICD9:943\ICD9:943.4\" NAME_CHAR="Deep necrosis of underlying tissues due to burn (deep third degree) of upper limb, except wrist and hand, without mention of loss of a body part" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:651.51" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:630-677\ICD9:651\ICD9:651.5\ICD9:651.51\" NAME_CHAR="Quadruplet pregnancy with fetal loss and retention of one or more fetus(es), delivered, with or without mention of antepartum condition" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:646.51" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:630-677\ICD9:646\ICD9:646.5\ICD9:646.51\" NAME_CHAR="Asymptomatic bacteriuria in pregnancy, with delivery" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
  <EK_TEMP_CONCEPT CONCEPT_CD="ICD9:653.20" CONCEPT_PATH="\EK\ICD9:Diagnoses\ICD9:630-677\ICD9:653\ICD9:653.2\ICD9:653.20\" NAME_CHAR="Inlet contraction of pelvis, unspecified as to episode of care in pregnancy" UPDATE_DATE="1970-02-15" DOWNLOAD_DATE="1970-02-15" IMPORT_DATE="2015-05-07" SOURCESYSTEM_CD="edu.emory.cci.aiw.i2b2etl.ksb.I2b2KnowledgeSourceB"/>
